version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/app
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./web/src:/app
